services:
  monitor:
    build: .
    command: python -m src.monitor.run_monitor
    volumes:
      - ./:/app
    working_dir: /app

  api:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
